default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fati
  password: fati123
  host: localhost

development:
  <<: *default
  database: nutritrack_development

test:
  <<: *default
  database: nutritrack_test

production:
  <<: *default
  database: nutritrack_production
  username: nutritrack
  password: <%= ENV["NUTRITRACK_DATABASE_PASSWORD"] %>
